# Generated by Django 5.1.5 on 2025-02-02 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="job_images/"),
        ),
    ]
